my.greeting: hello test
app:
name: my aapp
description : welcome to ${app.name}
list.values: one,two,three
db:
connection: URL
port: 1500
management.endpoints.web.exposure.include: "*"
server.port : 8090