my.greeting: hello ----
app:
name: my aapp
description : welcome to ${app.name}
list.values: one,two,three
db:
connection: URL
port: 500
management.endpoints.web.exposure.include: "*"
spring.profiles.active: test