name: Build and Deploy to AKS

on:
  push:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ACR_NAME: acrraj
  IMAGE_NAME: springboot-app
  RESOURCE_GROUP: springboot-aks-rg
  CLUSTER_NAME: springboot-aks-cluster

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Build JAR (IMPORTANT)
    - name: Build Spring Boot JAR
      run: mvn clean package -DskipTests

    # (Optional debug - can remove later)
    - name: List files
      run: ls -R

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    #Fixed Docker build
    - name: Build and Push Image to ACR
      run: |
        az acr build \
          --registry $ACR_NAME \
          --image $IMAGE_NAME:${{ github.sha }} \
          --file Dockerfile \
          .

    - name: Get AKS credentials
      run: |
        az aks get-credentials \
          --resource-group $RESOURCE_GROUP \
          --name $CLUSTER_NAME

    # Deploy update
    - name: Deploy to AKS
      run: |
        kubectl set image deployment/springboot-deployment \
        springboot=$ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

        kubectl rollout status deployment/springboot-deployment
